on: 
  push:
    branches: [ main ]
name: 🚀 Deploy dev version on devserver
jobs:
  shoptet-addon-deploy:
    uses: pavelhusa/addons-workflow-config/.github/workflows/dev.workflow.yml@main
    with:
      host: 'ftp.myshoptet.com'
      user: 'test_363432'
      remote-folder: /addonTest
    secrets:
      ftp_password: ${{ secrets.ftp_password }}